### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by Henry-Steele** [gabrc52/maingear-keyboard-lights#4]
Can we look into adding support for the 2022 version of the Maingear Vector Pro 2?

**Comment by gabrc52** [comment]
What keyboard light hardware does it have?

**Comment by Henry-Steele** [comment]
It uses an ITE Tech 8291 V0.3 - here is another utility I've been using in the past to control the keyboard lights, but your app has a handsome UI. https://github.com/pobrn/ite8291r3-ctl

Current udev rule I have going

SUBSYSTEM !="usb_device", ACTION !="add", GOTO="ite8291_rules_end"  
SYSFS{idVendor} =="048d", SYSFS{idProduct} =="6004", SYMLINK+="ite8291"
MODE="0666", OWNER="root", GROUP="root"
LABEL="ite8291_rules_end"

Modified the productId constant on ln 8 of /lib/models/contants.dart. Now the lights will turn on momentarily when choosing the turn on UI element, but then they turn off a second or two after.

**Comment by gabrc52** [comment]
I assume you'd also need to update e.g. https://github.com/gabrc52/maingear-keyboard-lights/blob/main/lib/models/light_control.dart so it does the same things as the Python script you linked.

**Comment by Henry-Steele** [comment]
Just to confirm there was some weirdness going going with the version of KDE I was on and some power management settings. Ended up getting rid of KDE and switching to a TWM without issue.

**Comment by gabrc52** [comment]
Strange. So did switching from KDE to a TWM make this app work?
